data = [
    # Positive
    ("i love this product", "positive"),
    ("this is amazing", "positive"),
    ("very good experience", "positive"),
    ("i am happy", "positive"),
    ("excellent quality", "positive"),
    ("best purchase ever", "positive"),
    ("highly recommend", "positive"),
    ("works perfectly", "positive"),
    ("so happy with this", "positive"),
    ("great value for money", "positive"),
    ("absolutely love it", "positive"),
    ("fantastic service", "positive"),
    ("this exceeded my expectations", "positive"),
    ("super satisfied", "positive"),
    ("awesome product", "positive"),
    ("i'm impressed", "positive"),
    ("5 stars", "positive"),
    ("very pleased with it", "positive"),

    # Negative
    ("this is bad", "negative"),
    ("i hate it", "negative"),
    ("very disappointing", "negative"),
    ("worst experience ever", "negative"),
    ("terrible quality", "negative"),
    ("complete waste of money", "negative"),
    ("do not buy", "negative"),
    ("broke after one use", "negative"),
    ("horrible customer service", "negative"),
    ("very poor quality", "negative"),
    ("extremely dissatisfied", "negative"),
    ("not worth it", "negative"),
    ("total garbage", "negative"),
    ("would not recommend", "negative"),
    ("disappointed", "negative"),
    ("cheap and flimsy", "negative"),
    ("stopped working", "negative"),

    # Neutral
    ("it's ok", "neutral"),
    ("not bad not good", "neutral"),
    ("average quality", "neutral"),
    ("it's decent", "neutral"),
    ("nothing special", "neutral"),
    ("okay i guess", "neutral"),
    ("meets basic expectations", "neutral"),
    ("standard product", "neutral"),
    ("it's fine", "neutral"),
    ("middle of the road", "neutral"),

    # More Positive
    ("this changed my life", "positive"),
    ("incredible experience", "positive"),
    ("thank you so much", "positive"),
    ("mind blowing", "positive"),
    ("top notch", "positive"),
    ("i'm obsessed with this", "positive"),
    ("fast delivery and great product", "positive"),

    # More Negative
    ("scam", "negative"),
    ("never buying again", "negative"),
    ("fraud", "negative"),
    ("very frustrating", "negative"),
    ("useless", "negative"),
    ("regret buying this", "negative"),
    ("broken on arrival", "negative"),

    # More Neutral / Mixed
    ("it's alright", "neutral"),
    ("does the job", "neutral"),
    ("average", "neutral"),
    ("good but expensive", "neutral"),
    ("not as good as expected", "neutral"),
    ("could be better", "neutral"),
    ("decent but not great", "neutral"),
]